[webserver]
port = ":8081"
hostname = "openstreetmap.doriangaliana.fr"
cors_allowed_origin = "*"

[cache]
type="file"             # cache type
basepath="/tmp/tegola"  # cache specific config

[[providers]]
max_connections = 20
host = "localhost"
name = "postgis"
database = "osm"
password = "osm"
srid = 3857
type = "postgis"
port = 5432
user = "osm"

    [[providers.layers]]
    name = "power_line"
    geometry_type = "LineString"
    sql = "SELECT gid, ST_AsBinary(geometry) AS geom, tunnel, location, first_semi(frequency) AS frequency, tags -> 'name' AS name, line, tags -> 'ref' AS ref, char_length(tags -> 'ref') AS ref_len, voltages[1] AS voltage, voltages[2] AS voltage_2, voltages[3] AS voltage_3, circuits, tags -> 'operator' AS operator, construction != '' AS construction, tags -> 'wikidata' AS wikidata, tags -> 'wikipedia' AS wikipedia, osm_url(tags) AS url FROM power_lines(!ZOOM!, !BBOX!) ORDER BY convert_voltage(voltage) ASC NULLS FIRST"

    [[providers.layers]]
    name = "power_tower"
    geometry_type = "Point"
    sql = "SELECT osm_id AS gid, ST_AsBinary(geometry) AS geom, type, tags -> 'name' AS name, transition, tags -> 'ref' AS ref, tags -> 'operator' AS operator, tags -> 'switch' AS switch, tags -> 'line_attachment' AS line_attachment, tags -> 'line_management' AS line_management, tags -> 'remotely_controllable' AS remotely_controllable, tags->'ref:FR:RTE' AS \"ref:FR:RTE\", tags->'ref:FR:gdo' AS \"ref:FR:gdo\", (ST_GeometryType(geometry) = 'ST_Point') AS is_node, construction != '' AS construction FROM osm_power_tower WHERE geometry && !BBOX! AND !ZOOM! >= 13"
    
    [[providers.layers]]
    name = "power_substation"
    geometry_type = "Polygon"
    sql = "SELECT osm_id AS gid, ST_AsBinary(geometry) AS geom, name, tags->'ref:FR:RTE' AS \"ref:FR:RTE\", tags->'ref:FR:gdo' AS \"ref:FR:gdo\", tags->'remotely_controllable' AS remotely_controllable, NULL AS frequency, convert_voltage(voltage) / 1000 AS voltage, convert_voltage(nth_semi(voltage, 2)) / 1000 AS voltage_2, convert_voltage(nth_semi(voltage, 3)) / 1000 AS voltage_3, substation, tags->'operator' AS operator, tags->'ref' AS ref FROM substation WHERE geometry && !BBOX! AND !ZOOM! >= 13 ORDER BY convert_voltage(voltage) ASC NULLS FIRST"

    [[providers.layers]]
    name = "power_substation_point"
    geometry_type = "Point"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Centroid(geometry)) AS geom, (ST_GeometryType(geometry) = 'ST_Point') AS is_node, round(ST_Area(geometry)) AS area, name, tags->'remotely_controllable' AS remotely_controllable, tags->'ref:FR:RTE' AS \"ref:FR:RTE\", tags->'ref:FR:gdo' AS \"ref:FR:gdo\", NULL AS frequency, convert_voltage(voltage) / 1000 AS voltage, convert_voltage(nth_semi(voltage, 2)) / 1000 AS voltage_2, convert_voltage(nth_semi(voltage, 3)) / 1000 AS voltage_3, substation, tags -> 'ref' AS ref, construction != '' AS construction, tags -> 'wikidata' AS wikidata, tags -> 'wikipedia' AS wikipedia, osm_url(tags) AS url FROM substation WHERE geometry && !BBOX! AND !ZOOM! >= 5 ORDER BY convert_voltage(voltage) ASC NULLS FIRST"

    [[providers.layers]]
    name = "power_plant"
    geometry_type = "Polygon"
    dont_simplify = true
    sql = "SELECT osm_id AS gid, ST_AsBinary(geometry) AS geom, name, tags -> 'operator' AS operator, convert_power(output)/1e6 AS output, first_semi(source) AS source, tags -> 'wikidata' AS wikidata, tags -> 'wikipedia' AS wikipedia, osm_url(tags) AS url, tags -> 'plant:storage' AS storage, tags -> 'repd:id' AS repd_id, tags -> 'construction:power' IS NOT NULL AS construction FROM power_plant WHERE geometry && !BBOX! AND !ZOOM! >= 11 ORDER BY convert_power(output) ASC NULLS FIRST"

    [[providers.layers]]
    name = "power_plant_point"
    geometry_type = "Point"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Centroid(geometry)) AS geom, round(ST_Area(geometry)) AS area, name, tags -> 'operator' AS operator, convert_power(output)/1e6 AS output, first_semi(source) AS source, tags -> 'wikidata' AS wikidata, tags -> 'wikipedia' AS wikipedia, osm_url(tags) AS url, tags -> 'plant:storage' AS storage, tags -> 'repd:id' AS repd_id, tags -> 'construction:power' IS NOT NULL AS construction FROM power_plant WHERE geometry && !BBOX! AND !ZOOM! >= 6 AND NOT ST_IsEmpty(geometry) ORDER BY convert_power(output) ASC NULLS FIRST"

    [[providers.layers]]
    name = "power_generator"
    geometry_type = "Point"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Centroid(geometry)) AS geom, tags -> 'name' AS name, tags -> 'operator' AS operator, convert_power(tags -> 'generator:output:electricity')/1e3 AS output, source, type, tags -> 'ref' AS ref, (ST_GeometryType(geometry) = 'ST_Point') AS is_node FROM osm_power_generator WHERE construction = '' AND geometry && !BBOX! AND !ZOOM! >= 9"

    [[providers.layers]]
    name = "power_heatmap_solar"
    geometry_type = "Point"
    sql = "SELECT ST_AsBinary(ST_SnapToGrid(ST_Centroid(geometry), ZRes(!ZOOM!), ZRes(!ZOOM!))) AS geom, round(sum(coalesce(convert_power(tags -> 'generator:output:electricity'), solar_output(geometry), 0)) / 1e3) AS output FROM osm_power_generator WHERE source = 'solar' AND construction = '' AND geometry && !BBOX! GROUP BY geom"

    [[providers.layers]]
    name = "power_generator_area"
    geometry_type = "Polygon"
    sql = "SELECT osm_id AS gid, ST_AsBinary(geometry) AS geom, tags -> 'name' AS name, tags -> 'operator' AS operator, convert_power(tags -> 'generator:output:electricity')/1e3 AS output, round(solar_output(geometry)/1e3) AS estimated_output, source, type, tags -> 'ref' AS ref FROM osm_power_generator WHERE geometry && !BBOX! AND construction = '' AND !ZOOM! >= 13 AND ST_GeometryType(geometry) = 'ST_Polygon'"

    [[providers.layers]]
    name = "power_transformer"
    dont_simplify = true
    geometry_type = "Point"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Centroid(geometry)) AS geom, tags -> 'name' AS name FROM osm_power_switchgear WHERE type = 'transformer' AND geometry && !BBOX! AND !ZOOM! >= 14"

    [[providers.layers]]
    name = "power_compensator"
    dont_simplify = true
    geometry_type = "Point"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Centroid(geometry)) AS geom, tags -> 'name' AS name FROM osm_power_switchgear WHERE type = 'compensator' AND geometry && !BBOX! AND !ZOOM! >= 14"

    [[providers.layers]]
    name = "power_switch"
    dont_simplify = true
    geometry_type = "Point"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Centroid(geometry)) AS geom, tags -> 'name' AS name, tags->'switch' AS switch FROM osm_power_switchgear WHERE type = 'switch' AND geometry && !BBOX! AND !ZOOM! >= 14"

    [[providers.layers]]
    name = "telecoms_communication_line"
    geometry_type = "LineString"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Simplify(geometry, ZRes(!ZOOM!) / 5, true)) AS geom, tags -> 'operator' AS operator, tags -> 'name' AS name, tags -> 'location' AS location FROM osm_telecom_cable WHERE tags -> 'construction:power' IS NULL AND geometry && !BBOX! AND 1 < !ZOOM! AND ST_Length(geometry) > ZRes(!ZOOM!) * 2"

    [[providers.layers]]
    geometry_type = "Polygon"
    name = "telecoms_sites"
    sql = "SELECT osm_id AS gid, ST_AsBinary(geometry) AS geom, operator, name, ref, \"ref:FR:ARCEP\", \"ref:FR:PTT\", \"ref:FR:Orange\",\"ref:FR:SFR\", telecom, \"telecom:medium\" FROM osm_telecom_sites_polygon WHERE geometry && !BBOX! AND !ZOOM! >= 10"

    [[providers.layers]]
    geometry_type = "Point"
    name = "telecoms_sites_points"
    sql = "SELECT osm_id AS gid, ST_AsBinary(geometry) AS geom, TRUE AS is_node, 0 AS area, operator, name, ref, \"ref:FR:ARCEP\", \"ref:FR:PTT\", \"ref:FR:Orange\",\"ref:FR:SFR\", telecom, \"telecom:medium\" FROM osm_telecom_sites_points WHERE geometry && !BBOX! AND !ZOOM! >= 10 UNION ALL SELECT osm_id AS gid, ST_AsBinary(ST_Centroid(geometry)) AS geom, FALSE AS is_node, round(ST_Area(geometry)) AS area, operator, name, ref, \"ref:FR:ARCEP\", \"ref:FR:PTT\", \"ref:FR:Orange\",\"ref:FR:SFR\", telecom, \"telecom:medium\" FROM osm_telecom_sites_polygon WHERE geometry && !BBOX! AND !ZOOM! >= 10"

    [[providers.layers]]
    name = "telecoms_mast"
    geometry_type = "Point"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Centroid(geometry)) AS geom, tags -> 'operator' AS operator, tags -> 'name' AS name, tags -> 'ref' AS ref, (ST_GeometryType(geometry) = 'ST_Point') AS is_node FROM osm_telecom_antennas WHERE (tags -> 'mast:type' IN ('communication', 'communications', 'broadcast') OR tags -> 'tower:type' IN ('communication', 'radio', 'antenna')) AND geometry && !BBOX! AND !ZOOM! >= 10"

    [[providers.layers]]
    name = "petroleum_pipeline"
    geometry_type = "LineString"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Simplify(geometry, ZRes(!ZOOM!) / 5, true)) AS geom, tags -> 'operator' AS operator, substance, tags -> 'name' AS name, tags -> 'location' AS location, tags -> 'ref' AS ref FROM osm_pipeline WHERE COALESCE(substance) IN ('natural_gas', 'gas', 'oil', 'fuel', 'cng') AND construction = '' AND geometry && !BBOX! AND ST_Length(geometry) > ZRes(!ZOOM!) * 2"

    [[providers.layers]]
    name = "petroleum_well"
    geometry_type = "Point"
    sql = "SELECT osm_id AS gid, ST_AsBinary(geometry) AS geom, tags -> 'operator' AS operator, tags -> 'name' AS name, tags -> 'ref' AS ref FROM osm_petroleum_well WHERE geometry && !BBOX! AND !ZOOM! >= 10"

    [[providers.layers]]
    name = "petroleum_site"
    geometry_type = "Polygon"
    sql = "SELECT osm_id AS gid, ST_AsBinary(geometry) AS geom, tags -> 'name' AS name, tags -> 'operator' AS operator, tags -> 'ref' AS ref FROM osm_petroleum_site WHERE geometry && !BBOX! AND !ZOOM! >= 8"

    [[providers.layers]]
    name = "water_ways"
    geometry_type = "LineString"
    sql = "SELECT osm_id AS gid, ST_AsBinary(ST_Simplify(geometry, ZRes(!ZOOM!) / 5, true)) AS geom, operator, name, waterway, tunnel, diameter, usage FROM osm_waterways WHERE geometry && !BBOX! AND !ZOOM! >= 3 AND ST_Length(geometry) > ZRes(!ZOOM!) * 2"

[[maps]]
name = "openinframap"
    [[maps.layers]]
    min_zoom = 2
    max_zoom = 17
    provider_layer = "postgis.power_line"

    [[maps.layers]]
    min_zoom = 13
    max_zoom = 17
    provider_layer = "postgis.power_tower"

    [[maps.layers]]
    min_zoom = 13
    max_zoom = 17
    provider_layer = "postgis.power_substation"

    [[maps.layers]]
    min_zoom = 5
    max_zoom = 17
    provider_layer = "postgis.power_substation_point"

    [[maps.layers]]
    min_zoom = 11
    max_zoom = 17
    provider_layer = "postgis.power_plant"

    [[maps.layers]]
    min_zoom = 2
    max_zoom = 17
    provider_layer = "postgis.power_plant_point"

    [[maps.layers]]
    min_zoom = 9
    max_zoom = 17
    provider_layer = "postgis.power_generator"

    [[maps.layers]]
    min_zoom = 2
    max_zoom = 17
    provider_layer = "postgis.power_heatmap_solar"

    [[maps.layers]]
    min_zoom = 13
    max_zoom = 17
    provider_layer = "postgis.power_generator_area"

    [[maps.layers]]
    min_zoom = 14
    max_zoom = 17
    provider_layer = "postgis.power_transformer"

    [[maps.layers]]
    min_zoom = 14
    max_zoom = 17
    provider_layer = "postgis.power_compensator"

    [[maps.layers]]
    min_zoom = 14
    max_zoom = 17
    provider_layer = "postgis.power_switch"

    [[maps.layers]]
    min_zoom = 2
    max_zoom = 17
    provider_layer = "postgis.telecoms_communication_line"

    [[maps.layers]]
    min_zoom = 10
    max_zoom = 17
    provider_layer = "postgis.telecoms_sites"

    [[maps.layers]]
    min_zoom = 8
    max_zoom = 17
    provider_layer = "postgis.telecoms_sites_points"

    [[maps.layers]]
    min_zoom = 10
    max_zoom = 17
    provider_layer = "postgis.telecoms_mast"

    [[maps.layers]]
    min_zoom = 2
    max_zoom = 17
    provider_layer = "postgis.petroleum_pipeline"

    [[maps.layers]]
    min_zoom = 10
    max_zoom = 17
    provider_layer = "postgis.petroleum_well"

    [[maps.layers]]
    min_zoom = 8
    max_zoom = 17
    provider_layer = "postgis.petroleum_site"

    [[maps.layers]]
    min_zoom = 3
    max_zoom = 17
    provider_layer = "postgis.water_ways"
